---
- name: Create new Active-Directory Domain & Forest
  hosts: winserver
  vars_files:
    - ../tf_ansible_vars_file.yml
  gather_facts: no
  tasks:

  - name: Check mandatory variables imported from Terraform
    assert:
      that:
        - dc_address is defined
        - dc_hostname is defined
      fail_msg: "tf_* variable usually defined in '..tf_ansible_vars_file.yml' is missing"

  - name: Wait for system to become reachable over WinRM
    wait_for_connection:
      timeout: 900

  - name: Set upstream DNS server 
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses:
      - '{{ upstream_dns_1 }}'
      - '{{ upstream_dns_2 }}'

  - name: Stop the time service
    win_service:
      name: w32time
      state: stopped

  - name: Set NTP Servers
    win_shell: 'w32tm /config /syncfromflags:manual /manualpeerlist:"{{ntp_servers}}"'

  - name: Start the time service
    win_service:
      name: w32time
      state: started  

  #Disable the windows firewall. Otherwise the domain firewall policy will prevent later tasks from succeeding after the system reboots. You can re-enable it and set rules to your liking once the playbook is complete.
  - name: Disable firewall for Domain, Public and Private profiles
    win_firewall:
      state: disabled
      profiles:
      - Domain
      - Private
      - Public
    tags: disable_firewall
  
  - name: Change the hostname 
    win_hostname:
      name: '{{ dc_hostname }}'
    register: res

  - name: Reboot
    win_reboot:
    when: res.reboot_required   

  # DEPLOY AD
  - name: Install Active Directory
    win_feature: >
        name=AD-Domain-Services
        include_management_tools=yes
        include_sub_features=yes
        state=present
    register: result

  - name: Create Domain
    win_domain: >
      dns_domain_name='{{ domain_name }}'
      safe_mode_password='{{ recovery_password }}'
    register: ad

  - name: reboot server
    win_reboot:
      msg: "Installing AD. Rebooting..."
      pre_reboot_delay: 15
    when: ad.changed

  - name: Set internal DNS server 
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses:
      - '127.0.0.1'

  - name: Create reverse DNS zone
    win_shell: "Add-DnsServerPrimaryZone -NetworkID {{reverse_dns_zone}} -ReplicationScope Forest" 
    retries: 30
    delay: 60
    register: result           
    until: result is succeeded

  # AD should be configured at this point, from here join the clients to the domain.